.github/CONTRIBUTING.md
New PRs will have the link to this file.
=> Add contributing.md file -> new PR will have the link to that file

Makefile, README.md, examples/cluster.yaml, examples/with-prepared-data.yaml, pom.xml, src/main/java/io/radanalytics/operator/ClusterInfo.java, src/main/java/io/radanalytics/operator/KubernetesDeployer.java, src/main/java/io/radanalytics/operator/ProcessRunner.java, src/main/java/io/radanalytics/operator/RunningClusters.java, src/main/java/io/radanalytics/operator/SparkOperator.java, src/main/java/io/radanalytics/operator/resource/HasDataHelper.java
it's both
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
=> Init containers that downloads data files for workers

manifest/kubernetes/rbac-kubernetes.yaml
unfortunately it doesn't w/ 3.7.x
=> Issue #34: this works also for OpenShift 3.9.0

.travis/.travis.test-oc.sh, Makefile, pom.xml, src/main/java/io/radanalytics/operator/Entrypoint.java, src/main/java/io/radanalytics/operator/cluster/ClusterInfo.java, src/main/java/io/radanalytics/operator/common/OperatorConfig.java
removing some (type) unsafe operations
adding some fine grade filtering for the shade plugin
also mvn cleaning helped a log
=> Fix #44: Getting rid of warnings in the build

.travis.yml, .travis/.travis.prepare.minikube.sh, .travis/.travis.prepare.openshift.sh, .travis/.travis.test-oc-and-k8s.sh, Makefile, src/main/java/io/radanalytics/operator/resource/HasDataHelper.java
opening this PR to make the travis do the build
=> travis.yml typo

helm/.helmignore, helm/Chart.yaml, helm/templates/operator.yaml, helm/values.yaml
test by
```
minikube start --vm-driver kvm2 --bootstrapper kubeadm
kubectl -n kube-system create sa tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller
kubectl -n kube-system get po
helm install ./helm
```
=> Fix #71: Add helm chart

.travis.yml, .travis/.travis.release.images.sh, Dockerfile.slim
=> auto-pushing of images also to quay.io

examples/cluster-with-config.yaml, src/main/java/io/radanalytics/operator/cluster/ClusterInfo.java, src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
further improvements captured in #79
=> Fix #77: add memory and cpu limits to pods

examples/cluster-with-config.yaml, src/main/java/io/radanalytics/operator/cluster/ClusterInfo.java, src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
make the travis happy:
now it fails with:
```
...
- lastProbeTime: null
lastTransitionTime: 2018-08-01T11:29:28Z
message: '0/1 nodes are available: 1 Insufficient cpu.'
reason: Unschedulable
status: "False"
...
```
=> Set the limits only if they are specified

Makefile, pom.xml, src/main/java/io/radanalytics/operator/app/AppOperator.java, src/main/java/io/radanalytics/operator/cluster/ClusterOperator.java
upgrading `abstract-operator` to `0.2.0` -> using simpler api
=> Simple api

pom.xml, src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
raising the versions of parent and the abstract-operator
=> version bumps

.travis/.travis.release.images.sh
todo1: create org in the quay currently it's still pushing to `jkremser`
todo2: change the org in the operator's manifest
@elmiko ptal
=> Fix #93: move from jkremser to radanalyticsio

.travis/.travis.test-oc-and-k8s.sh, manifest/olm-csv.yaml, manifest/operator-crd.yaml, manifest/operator.yaml
Github wouldn't let me reopen https://github.com/radanalyticsio/spark-operator/pull/106 see my final comment there.
=> Add resource limits to operator

.gitignore, Makefile
the manifests contain the `:latest-released` version of the image. So let's create a temp file with the `:latest` to be able to test the local changes quickly and iterate faster.
=> Make the 'make devel' work again

Dockerfile.alpine, Dockerfile.centos, manifest/olm-csv.yaml, manifest/operator-crd.yaml, manifest/operator.yaml
=> Use MaxRAMFraction=2 and icrease the limits from 400megs to 512

Makefile, pom.xml, src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
fix issue #115 
Each operator for each watched namespace runs periodically the full reconciliation routine. The interval is configurable by env property.
=> State reconciliation

.travis/.travis.test-oc-and-k8s.sh, .travis/.travis.test-restarts.sh, pom.xml
=> tests for metrics http server

.travis/.travis.test-oc-and-k8s.sh, .travis/.travis.test-restarts.sh, src/main/java/io/radanalytics/operator/app/KubernetesAppDeployer.java, src/main/resources/schema/sparkApplication.json
if not specified, it defaults to `spark-operator`
=> spark-apps: Allow for custom service account.

pom.xml
merge once abstract operator is released
Also the version of jsonschema2pojo is now declared in parent pom
=> Parent and abstract operator version bumps

.travis.yml, .travis/.travis.test-common.sh
Hopefully, this will help travis CI with the 'CreatingContainer' issue. Sometimes, the build failed because it wasn't able to create container for 5 minutes.
=> Docker img cache

.travis.yml, .travis/.travis.test-cross-ns.sh, helm/spark-operator/templates/operator.yaml, manifest/olm/crd/sparkclusteroperator.0.3.3.clusterserviceversion.yaml, manifest/operator.yaml, pom.xml
the logic is implemented in the abstract-operator, hence the version bump
=> Issue 173 : WATCHED_NAMESPACE -> WATCH_NAMESPACE

README.md
update the readme with a link to the gcp spark operator, and a note about similarities and differences.
#116
=> add note about gcp spark operator to readme

helm/spark-operator/Makefile, helm/spark-operator/README.md, helm/spark-operator/templates/operator.yaml, helm/spark-operator/values.yaml
`installNamespace` .. where the k8s resources are to be created
`watchNamespace` .. where the operator should watch for events
Fix #196 
=> Helm: Split the 'namespace' into 'installNamespace' and 'watchNamespace'

README.md
add a link to temaki into the readme to help people find it, if they desire.
none
=> add a link to oshinko-temaki in readme

README.md, manifest/operator-cm.yaml, manifest/operator.yaml, pom.xml
Opening the PR to let the travis verify it's ok to release a new version of the operator. Biggest change here is updating the abstract operator to a version, where `WATCH_NAMESPACE` means "watch all".
breaking change because of the `WATCH_NAMESPACE` semantics
=> pre-release version bumps, tweaks to readme

README.md
Link to existing ansible role for spark operator in the readme.
none
=> Mentioning the ansible role in the readme file.

.travis.yml, .travis/.travis.release.images.sh, .travis/cache/container-images-common.txt, Dockerfile.ubi, Makefile
Instead of using the centos images from fabric8, let's use the minimal UBIs w/ microdnf
#229 
=> Fix #229: rebase on UBI images

README.md
=> add note to readme about operator marketplace

src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
update the metrics when scaling
#239
=> Fix #239: update metrics when scaling workers

manifest/olm/crd/sparkcluster.crd.yaml, pom.xml, src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
~this requires the release of the abstract operator~
EDIT: ^ `0.6.9` is out
issue #246 
=> Add printer columns for SparkCluster crd

README.md
adding a line to the readme about the namespace variable
update the readme to have some info about changing the namespace variable for the role binding.
issue #260 was the inspiration for this
=> add a note to readme about namespace variable

pom.xml
let's see if Travis is ok w/ the version bumps
/cc @tmckayus
=> bump parent and abstract-operator versions
