radanalyticsio/spark-operator

- src/main/java/io/radanalytics/operator/KubernetesDeployer.java
- src/main/java/io/radanalytics/operator/SparkOperator.java
Adding support for deleting the clusters when we receive the DELETE event on configmap w/ the right label. For this we need to put the labels on all resources we create to make it easier to delete it later on.
#4 
~Updated docs / Refactor code / Added a tests case / Automation (non-breaking change)~
~Bug fix (non-breaking change which fixes an issue)~
~Breaking change (fix or feature that would cause existing functionality to change)~
> K8s delete cluster

- .travis.yml
- .travis/.travis.test-oc-and-k8s.sh
minikubes newer than `0.25.2` can't start properly on Travis CI, but the test suite can be run locally. New k8s has different output when creating objects hence the change in the "grepping" reg. expression.
> adjusting the test outputs to work against the new minikube

- pom.xml
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
- src/main/resources/schema/sparkCluster.json
In order to fix an issue with some strange type assignments (e.g. `getWorker()` returned a `Master` instance) I have upgraded the jsonschema2pojo plugin, made some small adjustments to the schema to ensure correct reuse/name of env/sparkConfiguration and updated the code to ensure it still compiles and passes unit tests. 
No issue, this was a follow up from https://github.com/radanalyticsio/spark-operator/pull/103 to resolve the issue with the types generated by jsonschema2pojo
> Upgrade jsonschema2pojo

- examples/cluster-cr-with-labels.yaml
- examples/cluster-with-labels.yaml
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/resources/schema/sparkCluster.json
Adding possibility to specify custom labels for kube resources. 
The labels in the spec.labels should be applied on all the resources we create in the K8s cluster, I.e. pods, services, RCs.
Those labels under spec.{woker|master}.labels should be applied only on the pods for worker or master.
Fixes #53
> custom labels for kube resources

- pom.xml
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
scaling the workers are handled in special manner, because the fabric8 client can't do similar thing as `kubectl apply`... the `createOrReplace` method will always destroy and create new, that is overkill in case of _ONLY_ scaling
Fix #131
> Fix #131 - recreate the cluster for other changes

- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
the liveness probe was failing for spark 2.4.0 with the full config example (because in the example also the limits were lower, both cpu and memory)
> Fix #142: initial delay for liveness probe

- examples/app.yaml
- src/main/java/io/radanalytics/operator/app/KubernetesAppDeployer.java
- src/main/resources/schema/sparkApplication.json
Make the sleep after spark-submit optional and configurable for the spark apps operator. If not specified the default is 1 year.
Nice side-effect of this change is the fact that once the sleep is done, the container finishes its work and the pod is killed and created again by the replication controller => repeated task.
In other words the `spark-submit` with the K8s as the native scheduler will be called in the `sleep n` intervals.
> Optional sleep for spark apps

- src/main/java/io/radanalytics/operator/app/AppOperator.java
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
Fixes issue #149 
For this use-case (cross-namespace functionality) the default manifests need to be slightly altered. To my knowledge it's not doable without `ClusterRole` and `ClusterRoleBinding` so this cross-namespace deployment requires cluster admin to create those resources in the first place.
> Fix #149: operator should deploy resources to the same namespace it is watching

- .travis.yml
- .travis/.travis.test-restarts.sh
- src/main/java/io/radanalytics/operator/cluster/RunningClusters.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
If the pod gets killed and new one is started, it should be able to continue with the work by doing some state reconciliation at the beginning. This PR adds the tests for this use case. It randomly kills the pod and does various asserts.
depends on issue #115
> Tests that restart the pod w/ operator

- pom.xml
- src/main/java/io/radanalytics/operator/cluster/MetricsHelper.java
- src/main/java/io/radanalytics/operator/cluster/RunningClusters.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
Improvement to the metrics:
- all the metrics can be now labeled by the namespace
- metric renamed: `operator_started_total` -> `operator_started_clusters_total`
- new metric for the number (counter) that tracks how many times the full reconciliation procedure has been run
- moving the concern that deals with metrics to it's own helper class
Also increasing the version of the abstract library and parent pom, this way the abstract library starts reporting also another useful information about the operator itself.. check https://github.com/jvm-operators/abstract-operator/commit/0273c20b427283f17cd697519b8c96ccaadf5739 for more details
> Metrics fu

- manifest/olm/crd/radanalytics-spark.package.yaml
- Adds radanalytics.package.yaml to OLM manifests to be used by
[Operator Lifecycle Manager (OLM)](https://github.com/operator-framework/operator-lifecycle-manager) to install, manage, and
upgrade the radanalytics sparkoperator in a cluster.
- The radanalytics sparkoperator versions available to all
Kubernetes clusters using OLM can be updated by submitting a pull
request to the [Community Operators GitHub repo](https://github.com/operator-framework/community-operators) that includes
the latest CSVs, CRDs, and Packages.
- For the sparkoperator, these are tracked in the community-operators repo [in this PR](https://github.com/operator-framework/community-operators/pull/45).
@Jiri-Kremser The package.yaml file is required for operators available through Operator Hub.
> Add sparkoperator Package for OLM and Operator Hub

- pom.xml
Run the `buildnumber-maven-plugin` that actually populates the `buildNumber` variable that is then filled by the maven-jar-plugin into the manifest. Check the https://git.io/fh9nF for more defails.
> missing git sha

- .travis/.travis.test-common.sh
- .travis/.travis.test-cross-ns.sh
- .travis/.travis.test-oc-and-k8s.sh
- .travis/.travis.test-restarts.sh
- README.md
- examples/app.yaml
- examples/apps/pyspark-ntlk.yaml
- examples/cluster-cr-with-labels.yaml
- examples/cluster-cr.yaml
- examples/cluster-with-config.yaml
- examples/cluster-with-labels.yaml
- examples/cluster.yaml
- examples/test/cluster-1.yaml
- examples/test/cluster-2.yaml
- examples/test/cluster-with-config-1.yaml
- examples/test/cluster-with-config-2.yaml
- examples/test/cluster-with-config-3.yaml
- examples/test/cr/app.yaml
- examples/test/cr/cluster-2.yaml
- examples/test/cr/cluster-with-config-1.yaml
- examples/test/cr/cluster-with-config-2.yaml
- examples/test/cr/cluster-with-config-3.yaml
- examples/with-prepared-data.yaml
- helm/spark-operator/README.md
- helm/spark-operator/templates/NOTES.txt
- manifest/olm/configmap-based-all-in-one-csv.yaml
- manifest/olm/crd/sparkapplication.crd.yaml
- manifest/olm/crd/sparkcluster.crd.yaml
- monitoring/example-cluster-with-monitoring.yaml
- pom.xml
This changes all sparkcluster objects to SparkCluster and all
sparkapplication to SparkApplication.
change all references to `sparkcluster` and `sparkapplication` to use the new `SparkCluster` and `SparkApplication` forms.
#179 
- [X ] Updated docs / Refactor code / Added a tests case / Automation (non-breaking change)
potentially breaking change for anyone using the older style object names.
do not merge this before, https://github.com/jvm-operators/abstract-operator/pull/29
> update spark entity names

- .travis/.travis.test-common.sh
- README.md
- helm/spark-operator/README.md
- helm/spark-operator/templates/operator.yaml
- manifest/operator-crd.yaml
- manifest/operator.yaml
- monitoring/Monitoring.md
- monitoring/example-cluster-with-monitoring.yaml
- monitoring/prometheus-operator.yaml
Fix: #187 
For CRDs we need to create ClusterRoleBinding resource that assigns a
ClusterRole to spark-operator ServiceAccount. The service account here
needs to have also the namespace. The only namespace we can assume
to be there is the ns called 'default'. Namespace called 'myproject'
is automatically created in openshift when running oc cluster up.
With K8s or OpenShift installed via Ansible it is not the case.
> Do not assume the myproject ns to be there

- src/main/java/io/radanalytics/operator/Constants.java
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
- src/main/resources/schema/sparkCluster.json
- src/test/java/io/radanalytics/operator/resource/YamlProcessingTest.java
This change makes it possible to set the default spark image through an
environment variable in the operator container. It also changes the
default image specified inside the code to
`quay.io/radanalyticsio/openshift-spark:latest` and removes the default
image ref from the schema spec.
#186
> change default spark image mechanics

- helm/spark-operator/templates/operator.yaml
Prevent that specifying * as namespace leads to an error while installing Helm chart
I was only able to install the Helm chart after adding quotes to the namespace value. We are using a YAML file to set the values that looks like this:
```
env:
crd: true
namespace: "*"
```
> Allow changing the deployment and watched namespace

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Changing the template for newly created PRs and issues to make it simpler and give contributors more freedom and "less processes". Also the check box approach for the type of change was awful, because GH was interpreting as a todo list.
@elmiko could you please take a look? Should it be even simpler?
> simplifying the templates for GH issue and PR

- examples/cluster-with-config.yaml
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
- src/main/resources/schema/sparkCluster.json
new boolean option in the CM or CR called `sparkWebUI`
todo: readiness probe logic, because it depended on the spark ui (it's done for master based on the open socket check), but it needs to be done also for workers, ideally by checking the log files if they were able to connect to the master
Issue #171 
> Make the spark ui optional (default=enabled)

- .travis/.travis.test-common.sh
- .travis/.travis.test-oc-and-k8s.sh
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
I was assuming that the curl returns something like: `<strong>Master URL: spark://172.17.0.7:7077</strong>` but it's not the case, it returns: `<strong>Master URL:</strong> spark://172.17.0.7:7077`. Travis was ok with the change, because the workers reported themselves as ready (readiness probe passed) and they passed the checks in travis, but when running the cluster for a minute it wasn't ok.
This PR also adds `-s` for the liveness probe for master, because what's important is the return code of the command and w/o the `-s` the curl returns that ugly header (also in `oc get events` output).
```
sh-4.2$ curl -s localhost:8081 | grep -e 'Master URL:.*spark://'
Master URL:</strong> spark://172.17.0.7:7077
sh-4.2$ echo $?
0
```
Fix #198 
:bug: Bug fix (non-breaking change which fixes an …
> Liveness probe for workers

- README.md
- examples/cluster-with-config.yaml
- examples/test/cluster-with-config-1.yaml
- examples/test/cm/cluster-with-config-1.yaml
- src/main/java/io/radanalytics/operator/cluster/InitContainersHelper.java
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/java/io/radanalytics/operator/cluster/MetricsHelper.java
Now when overriding the default Spark configuration, the mount will not shadow the other content in that directory anymore. This was the root cause for the #192 . Now the logic is as follows:
* Optionally adds the init containers that do:
* <ol>
*     <li>downloads the data with curl if it's specified</li>
*     <li>backups the original (default) Spark configuration into <code>NEW_CONF_DIR_PATH</code></li>
*     <li>copies/replaces the config files in the <code>NEW_CONF_DIR_PATH</code> with the files coming from the config map</li>
*     <li>overrides (/appends) the key-value entries in the <code>NEW_CONF_DIR_PATH/spark-defaults.conf</code></li>
*     <li>use the configuration <code>NEW_CONF_DIR_PATH</code> as the configuration for the spark</li>
* </ol>
where     `NEW_CONF_DIR_PATH` = …
> Init containers fix

- README.md
- src/main/java/io/radanalytics/operator/Constants.java
- src/main/java/io/radanalytics/operator/app/KubernetesAppDeployer.java
- src/main/resources/schema/sparkApplication.json
This change removes the default image set in the SparkApplication
schema and moves it to the constants definitions. It also adds a
function to detect the environment variable `SPARK_DEFAULT_APP_IMAGE` to
assist in overriding the default. Finally, the README is updated to
include instructions on configuring the operator.
#186 
> change SparkApplication default image mechanics

- src/main/java/io/radanalytics/operator/app/KubernetesAppDeployer.java
- src/main/java/io/radanalytics/operator/cluster/InitContainersHelper.java
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/resources/schema/sparkCluster.json
in the issue
Now, one can override the default commands that will be executed for master and worker nodes, example:
```yaml
apiVersion: radanalytics.io/v1
kind: SparkCluster
metadata:
name: my-spark-cluster
spec:
worker:
command:
- /bin/sh
- -c
commandArgs:
- sleep 500
```
issue #208 
> Customize image

- .travis.yml
- .travis/cache/.travis.before_cache.sh
- .travis/cache/.travis.before_install.sh
- .travis/cache/container-images-common.txt
- .travis/cache/container-images-k8s.txt
- .travis/cache/container-images-oc.txt
Using custom bash script that handle the save to and load from cache better than the one-liners previously specified in the `.travis.yml`
Especially the docker load operation is expensive, so for openshift stage it only loads those image that are specified on the white list for oc build. Similarly for the k8s stage. Previously, the cache mechanism was detecting the changes in the `~/.m2/repository`, therefore we now store the cache in `~/maven` and copy the content to and from the `~/.m2/repository`.
Fixes issue #221 
> Travis cache

- .travis/.travis.test-common.sh
- examples/cluster-with-config.yaml
- src/main/java/io/radanalytics/operator/cluster/InitContainersHelper.java
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/resources/schema/sparkCluster.json
before it runs the actual master/worker, it runs dummy/noop `spark-submit` command with `--packages` argument so that it can download the jars into `/tmp`. These are then reused when starting the nodes.
#213 
> Simple way to download maven artifact and use them for spark master and workers

- helm/spark-operator/templates/operator.yaml
- manifest/operator-cm.yaml
Spark operator deployments that use ConfigMaps instead of CRDs was throwing errors in the pod logs because it couldn't create a route for spark-operator-metrics --OR-- list pvcs.  This update will add CRUD for routes and get/list/watch for PVCs
N/A
> Add route & pvc permissions for operator-cm deployments

- manifest/operator.yaml
New versions of k8s don't work w/ v1beta1
To avoid this error (on minikube@1.5.2 w/ k8s@1.16.2):
```
error: unable to recognize "manifest/operator.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
```
/cc @elmiko
> [minor] changing the apiVersion for Deployment from apps/v1beta1 to apps/v1

- manifest/olm/crd/sparkcluster.crd.yaml
- pom.xml
- src/main/java/io/radanalytics/operator/app/AppOperator.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
- src/main/java/io/radanalytics/operator/historyServer/HistoryServerOperator.java
This adds basic status updates to the CRs managed by the spark operator. Status includes a state string and a lastTransitionTime field.  This PR is dependent on a change to the AbstractOperator in https://github.com/jvm-operators/abstract-operator/pull/62
As an initial pass, the status block available is fixed (string, date) and the changes should not break any existing subclasses of AbstractOperator class. In the future we can figure out how to add more general status.
The following issue is partly related. This is a first step toward general status, but it is mostly to satisfy failing CI in the community-operators repo because of the lack of a status block.
https://github.com/radanalyticsio/spark-operator/issues/216
> Add status subblock updatest to supported CRs

- .travis/.travis.test-common.sh
- .travis/.travis.test-oc-and-k8s.sh
- README.md
- examples/test/cluster-cpumem.yaml
- examples/test/cluster-limits.yaml
- examples/test/cluster-limreq.yaml
- examples/test/cluster-overwritelim.yaml
- examples/test/cluster-overwritereq.yaml
- examples/test/cluster-requests.yaml
- examples/test/cm/cluster-cpumem.yaml
- examples/test/cm/cluster-limits.yaml
- examples/test/cm/cluster-limreq.yaml
- examples/test/cm/cluster-overwritelim.yaml
- examples/test/cm/cluster-overwritereq.yaml
- examples/test/cm/cluster-requests.yaml
- src/main/java/io/radanalytics/operator/app/AppOperator.java
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
- src/main/java/io/radanalytics/operator/historyServer/HistoryServerOperator.java
- src/main/resources/schema/sparkCluster.json
Previously a SparkCluster allowed an optional value for cpu
and memory that was used to set both the limit and request
value for each. This change adds new optional fields to
individually set request and limit values.
To preserve backward compatibility:
* if just "cpu" or "memory" are set, the behavior is unchanged
* "cpuRequest" and "memoryRequest" will take precedence over
values from "cpu" or "memory" for setting request values
* "cpuLimit" and "memoryLimit" will take precedence over
values from "cpu" or "memory" for setting limit values
> Add new request and limit values to SparkCluster CR for cpu and memory

- src/main/java/io/radanalytics/operator/app/AppOperator.java
- src/main/java/io/radanalytics/operator/cluster/SparkClusterOperator.java
- src/main/java/io/radanalytics/operator/historyServer/HistoryServerOperator.java
add overloads in SparkApplication and SparkHistoryServer for
onModify and test whether the object has actually changed before
calling the super method.
> Ignore onModify if only the status block has changed

- .travis/cache/container-images-common.txt
- examples/app.yaml
- examples/test/cm/app.yaml
- src/main/java/io/radanalytics/operator/Constants.java
some of the app examples are using older versions of spark 2.3.
on current versions of openshift, spark-on-k8s does not work
for spark versions before 2.4.5
> Use radanalyticsio/openshift-spark:2.4-latest or 2.4.5-2 for apps

- .travis/.travis.test-common.sh
- .travis/.travis.test-oc-and-k8s.sh
- README.md
- examples/test/cluster-node-tolerations.yaml
- examples/test/cm/cluster-node-tolerations.yaml
- src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
- src/main/resources/schema/sparkCluster.json
This adds support to the operator for a user to be able to specify a set
of Node Tolerations to be applied to the pods in a cluster.
> Allow user to specify Node Tolerations for cluster pods

- spark-operator/src/main/java/io/radanalytics/operator/cluster/InitContainersHelper.java
- spark-operator/src/main/resources/schema/sparkCluster.json
Very simple change that adds in the ability to configure the init container image used and if not specified then defaults to previous behaviour.
tackles issue #326
> Added a new optional parameter to the SparkCluster CRD to specify init container image

- examples/test/cluster-node-tolerations.yaml
- examples/test/cm/cluster-node-tolerations.yaml
- spark-operator/src/main/java/io/radanalytics/operator/cluster/KubernetesSparkClusterDeployer.java
I discovered a bug that prevents a user from being able to specify Node
Tolerations with the "NoSchedule" effect. These types of tolerations do
not have the "tolerationSeconds" setting, and Kubernetes complains if
you attempt to set them. My previous implementation did not properly
allow for creating a toleration when the tolerationSeconds setting was
not specified.
None
> Fix a bug when specifying NoSchedule node tolerations

- examples/test/history-server/externalStorage/ceph-nano.yaml
- helm/spark-operator/templates/operator.yaml
- manifest/olm/configmap-based-all-in-one-csv.yaml
- manifest/operator-cm.yaml
- monitoring/example-cluster-with-monitoring.yaml
- monitoring/prometheus-operator.yaml
Change Deployments and StatefulSets to apps/v1
Change rbac.authorization.k8s.io to v1
https://kubernetes.io/docs/reference/using-api/deprecation-guide/
> Update k8s APIs from deprecated versions
